stages:
  - deploy
  - undeploy

before_script:
  - apt-get update && apt-get install -y rsync openssh-client
  - mkdir -p ~/.ssh
  - PRIVATE_KEY_DECODED="$(cat $DEPLOY_PRIVATE_KEY | base64 -d)"
  - echo "$PRIVATE_KEY_DECODED" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

# Template de l'action de déploiement
.deploy_template: &deploy_template
  stage: deploy
  image: debian:bullseye
  when: manual
  script:
    - |
      cat <<EOF > ./$ENV/.private.env
      POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      POSTGRES_USER=$POSTGRES_USER
      BEARER_TOKEN_TDMB=$TMDB_TOKEN
      EOF
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no movierizer@$SERVER_IP "mkdir -p /home/movierizer/movierizer"
    - rsync -avz --delete ./ movierizer@$SERVER_IP:/home/movierizer/movierizer
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no movierizer@$SERVER_IP "cd /home/movierizer/movierizer/$ENV && docker compose up -d"    


# Template de l'action de suppression du déploiement
.undeploy_template: &undeploy_template
  stage: undeploy
  image: debian:bullseye
  when: manual
  script:
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no movierizer@$SERVER_IP "cd /home/movierizer/movierizer/$ENV && docker compose down"
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no movierizer@$SERVER_IP "rm -rf /home/movierizer/movierizer"

.deploy_dev:
  <<: *deploy_template
  stage: deploy
  environment:
    name: dev
  only:
    - /^feat/.*$/
    - /^fix/.*$/

deploy_prod:
  <<: *deploy_template
  stage: deploy
  environment:
    name: prod
  only:
    - main
    - develop
    - fix/ci

.undeploy_dev:
  <<: *undeploy_template
  stage: undeploy
  environment:
    name: dev
  only:
    - /^feat/.*$/
    - /^fix/.*$/

undeploy_prod:
  <<: *undeploy_template
  stage: undeploy
  environment:
    name: prod
  only:
    - main
    - develop
