stages:
  - deploy

deploy:
  stage: deploy
  image: debian:bullseye
  before_script:
    - apt-get update && apt-get install -y rsync openssh-client
    - mkdir -p ~/.ssh
    - PRIVATE_KEY_DECODED="$(cat $DEPLOY_PRIVATE_KEY | base64 -d)"
    - echo "$PRIVATE_KEY_DECODED" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 217.182.104.218 >> ~/.ssh/known_hosts
  script:
    - rsync -avz --delete ./ movierizer@217.182.104.218:/home/movierizer/movierizer