services:
  db:
    image: s0nren/movierizer-database:${DB_VERSION}
    pull_policy: always
    container_name: movierizer_db
    restart: always
    env_file:
      - .env
      - .private.env
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  back:
    image: s0nren/movierizer-api:${API_VERSION}
    pull_policy: always
    container_name: movierizer_api
    restart: always
    env_file:
      - .env
      - .private.env
    ports:
      - "8081:5000"
    networks:
      - backend
      - frontend
    depends_on:
      - db
      
  front:
    image: s0nren/movierizer-front:${FRONT_VERSION}
    pull_policy: always
    container_name: movierizer_front
    restart: always
    env_file:
      - .env
    ports:
      - "8080:3000"
    networks:
      - frontend
    depends_on:
      - back

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge

volumes:
  pgdata: